# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: azure-alpine-test
    containerRegistry: jvazurecontainerregistry
    tags: |
      latest
- script: |
    docker run -e ANCHORE_CLI_URL=$ENGINEURL -t anchore/engine-cli anchore-cli image add jvtestregistry.azurecr.io/azure-alpine-test:latest
    docker run -e ANCHORE_CLI_URL=$ENGINEURL -t anchore/engine-cli anchore-cli image wait jvtestregistry.azurecr.io/azure-alpine-test:latest
    docker run -e ANCHORE_CLI_URL=$ENGINEURL -t anchore/engine-cli anchore-cli evaluate check jvtestregistry.azurecr.io/azure-alpine-test:latest
  displayName: 'scan image with anchore'
  env:
    ANCHOREURL: $(anchore-engine-url)