# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: | 
    docker build -t azure-alpine-test .
    docker tag azure-alpine-test:latest jvtestregistry.azurecr.io/azure-alpine-test:latest
    docker push jvtestregistry.azurecr.io/azure-alpine-test:latest
  displayName: 'build and push image to ACR'