# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: azure-alpine-test
    containerRegistry: jvazurecontainerregistry
    tags: |
      latest
- script: docker run -e ANCHORE_CLI_URL=$anchore-engine-url -t anchore/engine-cli anchore-cli system status
  displayName: 'scan image with anchore'
  env:
    ANCHOREURL: $(anchore-engine-url)